/*FIRST TIME USE SQL SCRIPT*/

CREATE DATABASE BOAT_MONITOR;

USE BOAT_MONITOR;

CREATE TABLE HISTORICS
(
    id INTEGER NOT NULL AUTO_INCREMENT,
    container_status TEXT NOT NULL,
    container_weight FLOAT NOT NULL,
    boat_location TEXT NOT NULL,
    dt DATETIME NOT NULL,

    PRIMARY KEY(ID)
);

CREATE TABLE FILES
{
    id INTEGER NOT NULL AUTO_INCREMENT,
    fl_name TEXT NOT NULL,
    fl_type TEXT NOT NULL,
    fl_url TEXT NOT NULL,
    dt DATETIME NOT NULL,

    PRIMARY KEY(ID)
}