/*FIRST TIME USE SQL SCRIPT*/

CREATE DATABASE BOAT_MONITOR;

USE BOAT_MONITOR;

CREATE TABLE HISTORICS
(
    id INTEGER NOT NULL AUTO_INCREMENT,
    container_status TEXT NOT NULL, --'OPEN' OR 'CLOSED'
    container_weight FLOAT NOT NULL, --KG
    boat_location TEXT NOT NULL, --LAT, LONG? gOOGLE COMPATIBLE
    dt DATETIME NOT NULL,
    fl_name TEXT NOT NULL,
    reg DATETIME NOT NULL

    PRIMARY KEY(ID)
);

CREATE TABLE FILES
{
    id INTEGER NOT NULL AUTO_INCREMENT,
    fl_name TEXT NOT NULL,
    fl_type TEXT NOT NULL,
    fl_url TEXT NOT NULL,
    dt DATETIME NOT NULL,
    reg DATETIME NOT NULL

    PRIMARY KEY(ID)
}